### ISSUE TITLE
Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet play/90 (class_2751) was larger than I expected, found 51 bytes extra whilst reading packet 90

### ISSUE THREAD

**Issue by RalphORama** [WiIIiam278/Velocitab#100]
When I install Velocitab on my proxy and try to connect, I am consistently kicked with this error message:

```
Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet play/90 (class_2751) was larger than I expected, found 51 bytes extra whilst reading packet 90
```

No errors in console on the proxy or backend. It's a client-side error.

## Software Info

- Velocity 3.2.0-SNAPSHOT (`git-2bd2c692-b269`)
- Velocitab v1.4.1
- Client version 1.20.2

**Comment by WiIIiam278** [comment]
We haven't released a version that supports1.20.2 yet. we are working on it, but it's not ready yet :)

**Comment by RalphORama** [comment]
Ok! Ty for the awesome plugin
