### ISSUE TITLE
vanishPlayer API does not work

### ISSUE THREAD

**Issue by TwinkleToes777** [WiIIiam278/Velocitab#113]
java.lang.NullPointerException: Cannot invoke "String.length()" because "teamName" is null
       at net.william278.velocitab.packet.UpdateTeamsPacket.removeTeam(UpdateTeamsPacket.java:120)
       at net.william278.velocitab.packet.ScoreboardManager.vanishPlayer(ScoreboardManager.java:89)
       at net.william278.velocitab.vanish.VanishManager.lambda$vanishPlayer$0(VanishManager.java:63)
       at java.base/java.util.Optional.ifPresent(Optional.java:178)
       at net.william278.velocitab.vanish.VanishManager.vanishPlayer(VanishManager.java:63)
       at net.william278.velocitab.api.VelocitabAPI.vanishPlayer(VelocitabAPI.java:154)

           @Subscribe
    public void onJoin(ServerPostConnectEvent event) {
        	plugin.getVelocitabAPI().vanishPlayer(event.getPlayer());
    }

**Comment by alexdev03** [comment]
Hi, maybe this is a syncronization issue as you are vanishing the player before he can handled by velocitab. I'm adding an event you can listen to.

**Comment by alexdev03** [comment]
@TwinkleToes777 
Hi, could you try the latest build of velocitab with this new [api version](https://repo.william278.net/#/snapshots/net/william278/velocitab/1.5.2-c36e17b). Use the new [PlayerAddedToTabEvent](https://william278.net/docs/velocitab/api-examples#_3-listening-to-playeraddedtotabevent) to listen when a player is loaded and then use the vanish api.

**Comment by TwinkleToes777** [comment]
how to get player in this new event? I tried event.getPlayer() and event.getPlayer().getPlayer(), all throw compile errors

**Comment by alexdev03** [comment]
Could you send the stack trace pls and the code you are using.

**Comment by TwinkleToes777** [comment]
> Could you send the stack trace pls and the code you are using.

There is no stacktrace as the code does not compile, it throws compile-time error: "no symbol found" on event.getPlayer() inside PlayerAddedToTabEvent, the event itself compiles correctly, just event.getPlayer() does not

**Comment by alexdev03** [comment]
Try with player(), check rhe docs 
[here](https://william278.net/docs/velocitab/api-examples#_3-listening-to-playeraddedtotabevent)

**Comment by WiIIiam278** [comment]
@alexdev03 oh, I didn't notice that. I'd prefer us to not use lombok in this class and add a `getPlayer` method

**Comment by WiIIiam278** [comment]
@TwinkleToes777 have you tried, using the latest API snapshot, calling `#getPlayer()`? you'll need to install the latest alpha on your proxy from modrinth. let me know.

**Comment by TwinkleToes777** [comment]
> @TwinkleToes777 have you tried, using the latest API snapshot, calling `#getTabPlayer()`? you'll need to install the latest alpha on your proxy from modrinth. let me know.

No error, no vanish.

**Comment by alexdev03** [comment]
@TwinkleToes777 
In order to vanish a player you need to provide a vanish integration. [1.3](https://william278.net/docs/velocitab/api-examples#_1-vanishingun-vanishing-a-player) otherwise velocitab will use the default one. 
Vanish Integration is a system to provide velocitab a way to check if a player can see another player.
