### ISSUE TITLE
Better luckperms integration and sorting issues

### ISSUE THREAD

**Issue by xHyroM** [WiIIiam278/Velocitab#120]
###  Sorting breaks when you give an online player a group via LuckPerms

You can actually solve it by `update_rate`, but isn't there should be an integration?

**Comment by alexdev03** [comment]
Could you send a video of the problem? Which version are you using?

**Comment by xHyroM** [comment]
> Could you send a video of the problem? Which version are you using?
v1.5.1

https://github.com/WiIIiam278/Velocitab/assets/56601352/8ddb04f1-9ef4-47d5-8d3a-7122917a9730

**Comment by alexdev03** [comment]
Hi could you this dev build please? Restart or If you want you can use a plugin manager to reload the plugin.
[Velocitab-1.5.2-39d2a9a-indev.zip](https://github.com/WiIIiam278/Velocitab/files/13322704/Velocitab-1.5.2-39d2a9a-indev.zip)

**Comment by xHyroM** [comment]
> Hi could you this dev build please? Restart or If you want you can use a plugin manager to reload the plugin. [Velocitab-1.5.2-39d2a9a-indev.zip](https://github.com/WiIIiam278/Velocitab/files/13322704/Velocitab-1.5.2-39d2a9a-indev.zip)

Sorry for late response, yes, this works great!

**Comment by alexdev03** [comment]
perfect

**Comment by WiIIiam278** [comment]
Closed by #119
