### ISSUE TITLE
"Offline mode" setups using auth plugins can experience duplicate TAB entries

### ISSUE THREAD

**Issue by xHyroM** [WiIIiam278/Velocitab#121]
![image](https://github.com/WiIIiam278/Velocitab/assets/56601352/58cf804b-af96-41a3-8d72-c361164c5805)
![image](https://github.com/WiIIiam278/Velocitab/assets/56601352/4bd0a8ff-d24f-440c-a9e0-9793c991a697)
![image](https://github.com/WiIIiam278/Velocitab/assets/56601352/61662f93-7f8f-46f2-be9d-79be65ebf9f6)

Some players see themselves 2x in the tab, the server is running on version 1.20 with viaversion, I personally have 1.20.1 and I see myself once, one of those who see themselves 2x has 1.20 and the other one also has 1.20.1

Version: v1.5.1

**Comment by WiIIiam278** [comment]
can you try with the latest _alpha_ release of Velocitab? https://modrinth.com/plugin/velocitab

**Comment by WiIIiam278** [comment]
also; are you using the API to change user names at all?

**Comment by xHyroM** [comment]
> also; are you using the API to change user names at all?

No no, and I'll try the alpha build tomorrow.

**Comment by alexdev03** [comment]
Are you still using the build I gave you for the other issue?

**Comment by xHyroM** [comment]
> Are you still using the build I gave you for the other issue?

If you mean a build that includes luckperms recalculation event then yep

**Comment by alexdev03** [comment]
Did this problem occur also with the previous version that were you using?

**Comment by xHyroM** [comment]
> Did this problem occur also with the previous version that were you using?

If you mean v1.5.1 (latest), yes

**Comment by alexdev03** [comment]
Can you please open a ticket on Discord? We can discuss the problem further there.

**Comment by xHyroM** [comment]
> Can you please open a ticket on Discord? We can discuss the problem further there.

Okay, sorry for late response

**Comment by GIGABAIT93** [comment]
I have this problem too version 1.5.2
![зображення](https://github.com/WiIIiam278/Velocitab/assets/59637348/c3f61dbc-0340-438f-b313-c70cf8e380f1)

**Comment by GIGABAIT93** [comment]
Maybe it's because my server uses an offline uuid?

**Comment by GIGABAIT93** [comment]
i tried all versions 1.5.2 and all of them have double nickname problem in version 1,5,1 no such problem but custom nickname is not formatted.
Plugins: azlink, cmiv, discord, floodgate, geyser, leaf, protocolize, librelogin, limboapi, litebans, luckperms, papiproxybridge, plasmovoice, pv-addon-broadcast, pv-addon-groups, skinsrestorer, velocitab, velocityresourcepacks

**Comment by xHyroM** [comment]
My issue is with LimboAuth and /premium feature:

![image](https://github.com/WiIIiam278/Velocitab/assets/56601352/0146b14d-ab8d-484d-919e-0e16dc50e582)

**Comment by GIGABAIT93** [comment]
> My issue is with LimboAuth and /premium feature:
> 
> ![image](https://private-user-images.githubusercontent.com/56601352/291615577-0146b14d-ab8d-484d-919e-0e16dc50e582.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5OTY5OTMsIm5iZiI6MTcwMjk5NjY5MywicGF0aCI6Ii81NjYwMTM1Mi8yOTE2MTU1NzctMDE0NmIxNGQtYWI4ZC00ODRkLTkxOWUtMGUxNmRjNTBlNTgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE0MzgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmMGZiYmVhNDY0NDVkMzFiMzg4OGE2MjNkYmE0OWVjMTNhYWYxMzU2MzRlYjY2YWY2ODgzNzNlZTViNzMwZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RSrGQEDtpTAd9owPTMcQvbYNt7L6C9SXDjKRl3tRxeU)

you use floodgate, geyser?Because I don't use LimboAuth but have the same problem

**Comment by GIGABAIT93** [comment]
i'm using librelogin and i have /premium enabled

**Comment by xHyroM** [comment]
> > My issue is with LimboAuth and /premium feature:
> 
> you use floodgate, geyser?Because I don't use LimboAuth but have the same problem

nope, i dontuse geyser and floodgate.

**Comment by xHyroM** [comment]
> i'm using librelogin and i have /premium enabled

try to disable premium

**Comment by WiIIiam278** [comment]
This bug seems to only occur with servers using cracked setups with auth plugins doing weird stuff. If we find a fix for it then we'll add it, but to be honest this is gonna be low priority to investigate as I don't really support non-premium setups \:)
