### ISSUE TITLE
Add option to periodically update the TAB list

### ISSUE THREAD

**Issue by WiIIiam278** [WiIIiam278/Velocitab#13]
I've noticed that the tab list is not periodically updated. 

I'd like for the tablist to be periodically updated, lets say every 10 or 30 seconds (or a configurable amount of time), so that the current server time is accurately reflected for our configuration, and so that the players current ping is also updated. We have both displayed in the tablist.

**Comment by WiIIiam278** [comment]
I think this doesnt actually work since the update method only updates it for the one player

**Comment by ironboundred** [comment]
![2023-03-07_11 33 35](https://user-images.githubusercontent.com/44921987/223505020-2070283e-300b-47ad-8dfe-b331621b6d54.png)

![2023-03-07_11 33 37](https://user-images.githubusercontent.com/44921987/223505021-94a4ab8e-a605-446d-9299-b24ed2bb476f.png)

I am not having an issue with it updating after the merged PR? I have it set at 500 for the update rate.

**Comment by WiIIiam278** [comment]
Can't reproduce right now, closing
