### ISSUE TITLE
Are there plans to support older Velocity versions in the future?

### ISSUE THREAD

**Issue by KiWinger** [WiIIiam278/Velocitab#136]
3.3.0 In beta phase frequently updated, so use 3.2.0 compared to 3.3.0 more stable, but does not support the latest version 1.5.2, if use the old version [Velocitab] can not get BUG fix.
Are there plans to support older Velocity versions in the future?

**Comment by WiIIiam278** [comment]
No, 3.3.0 is "experimental" but stable and supports MC 1.8-1.20.4. I need to target Velocity 3.3.0 to support MC 1.20.4, so that's the new minimum version requirement.
