### ISSUE TITLE
Add Server Name Formatting

### ISSUE THREAD

**Issue by Boy0000** [WiIIiam278/Velocitab#14]
Basically let you map %server% to specific strings, to make it not just use the velocity server id, but something configurable.
Convo context: https://discord.com/channels/818135932103557162/1082004976227848192

**Comment by Emibergo02** [comment]
since I need this feature too, I'll PR something next week

**Comment by WiIIiam278** [comment]
Done in https://github.com/WiIIiam278/Velocitab/commit/28c5398c6b313aa44cec56f9d11b5e46aeaa05b3
