### ISSUE TITLE
Velocitab 1.6 doesn't work with newest Velocity version

### ISSUE THREAD

**Issue by jamesn1208** [WiIIiam278/Velocitab#145]
Velocity 3.3.0 released recently, I run my network through docker image, auto restart occurred @ 6am this morning, and with it the newest version of Velocity was pulled, leading to me being unable to join with the following error (interim sln is deleting Velocitab until update). See screenshot for server log (velocity log).

<img width="1266" alt="image" src="https://github.com/WiIIiam278/Velocitab/assets/132159006/ebe37453-17b4-4bbd-b2b3-440974de77fa">

**Comment by alexdev03** [comment]
Hi, this problem should have benn fixed in this [version ](https://modrinth.com/plugin/velocitab/version/1.6.1-8bace56).

**Comment by jamesn1208** [comment]
Was just writing a follow up to say that I hadn't seen the alpha versions & am testing it;
It works, may want to add a note somewhere to avoid more of these issues like mine when it's already fixed :)

**Comment by WiIIiam278** [comment]
We just fixed this and plan on releasing a version update soon once we've done stability testing :)
