### ISSUE TITLE
Support Minecraft protocol vers 1.16.5, 1.17.1, 1.18.2

### ISSUE THREAD

**Issue by Teastrands** [WiIIiam278/Velocitab#15]
Not sure if this causes any issues but thought I would share anyway.

https://pastebin.com/csTUtJbr

**Comment by WiIIiam278** [comment]
velocitab is only compatible with 1.19, 1.19.1, 1.19.2 and 1.19.3 servers -- if your network is running other servers it won't work

**Comment by Teastrands** [comment]
Thanks! It half works if that's any consolation. I get the correct tab list across my servers.

**Comment by WiIIiam278** [comment]
Gonna leave this open as I do want to do this

**Comment by WiIIiam278** [comment]
Done in a7d512e6fe672b00e81b8237cd76544db4d28676, now supports clients from Version 1.13 technically (though I'm only targeting 1.16.5+)
