### ISSUE TITLE
Couldn't pass ProxyInitializeEvent to velocitab

### ISSUE THREAD

**Issue by TheNoobestPlayer** [WiIIiam278/Velocitab#159]
The plugin act as normal when first installed. But after the first launch I can always get this error message.
(I didn't do anything to the config.yml . To do a test I delete the whole config folder and relaunch the server. And got the same error on the second launch)
Using Velocity3.3.0

Logs: https://pastebin.com/9UhEbNqW

**Comment by alexdev03** [comment]
hi, which velocitab version are you using?

**Comment by TheNoobestPlayer** [comment]
Hi I use latest velocitab and latest Velocity build

**Comment by WiIIiam278** [comment]
Already fixed in 63ed22527b75ba505ad94bb538307d46f8d209d6

Please use the latest Modrinth alpha version: https://modrinth.com/plugin/velocitab/versions
