### ISSUE TITLE
Problems that occur when running plugin on the mohist server

### ISSUE THREAD

**Issue by Hakuyako** [WiIIiam278/Velocitab#160]
I'm running this plugin in a mohist server, the plugin runs well except for one problem:

When I installed the plugin on the server, all passive mobs stopped spawning naturally and the spawners stopped spawning new mobs, however the spawning of hostile mobs work correctly.This may be related to a flag that controls mob spawning.

I have purchased your plugin in spigot and I would be very grateful if you can  fix this issue.

**Comment by WiIIiam278** [comment]
You appear to have filed this issue in the wrong repository? \:)
