### ISSUE TITLE
Add parameter to skip Velocity version and build check

### ISSUE THREAD

**Issue by Joo200** [WiIIiam278/Velocitab#161]
Self compiled velocity server versions are not compatible with Velocitab because Velocitab extracts the build number from the version string.

To allow development of Velocity itself or running on self compiled Velocity versions (and Velocity forks) there should be a parameter to disable the metadata version check, e.g. `-velocity-unsafe-environment=true`

This should bypass the parsing and version check completly

**Comment by alexdev03** [comment]
`-Dvelocitab.skip-compatibility-check=true` should work
