### ISSUE TITLE
Is it possible to make it compatible with Fabric Carpet's TAB bar?

### ISSUE THREAD

**Issue by RedSnailMC** [WiIIiam278/Velocitab#164]
When I use Velocitab in conjunction with Fabric Carpet's info TAB bar, it appears that the two are displayed alternately with each other, 
Like this:

https://github.com/WiIIiam278/Velocitab/assets/102704717/778e61c1-1d66-45ab-aa3f-4103ff19f77a

Is there a way to make them compatible with each other?

**Comment by ProdPreva1l** [comment]
You can set the footer in velocitab to the placeholders to display that information

**Comment by WiIIiam278** [comment]
Hey - so no, you can only use one tab mod / plugin at once or you'll get conflicts. If you need to display info on your tab from fabric servers use papiproxybridge + the placeholder api mod :)

**Comment by WiIIiam278** [comment]
I hope that answers your question :) If you have further questions/comments, get in touch on Discord.
