### ISSUE TITLE
[BUG] [papiproxybridge]: Failed to format placeholders for Moxitop

### ISSUE THREAD

**Issue by KiWinger** [WiIIiam278/Velocitab#171]
- PlaceholderAPI-2.11.5
- PAPIProxyBridge-1.5
- Velocitab-1.6.3

The console keeps outputting: 
`[22:11:58 INFO] [papiproxybridge]: Failed to format placeholders for Moxitop`

Cannot pass when using PAPI variables.
![java_BJODzc3KBz](https://github.com/WiIIiam278/Velocitab/assets/49084827/2903259b-e175-4be6-b877-58bd5a6fe85b)

Involve:
server, player, vault
The corresponding extension plugin has been installed.

**Comment by alexdev03** [comment]
Hi, do you have papiproxybridge installed on backends?

**Comment by KiWinger** [comment]
> Hi, do you have papiproxybridge installed on backends?

No, only PlaceholderAPI-2.11.5

**Comment by alexdev03** [comment]
Please follow this guide https://william278.net/docs/velocitab/placeholders#placeholderapi-support.
