### ISSUE TITLE
[Q] Unable to set font color when using the "Customizing server display names" function?

### ISSUE THREAD

**Issue by KiWinger** [WiIIiam278/Velocitab#172]
Unable to set font color when using the "Customizing server display names" function? 
May I ask how to set the identification of each server to different colors within a server?

**Comment by WiIIiam278** [comment]
I think you'd just put the color before the custom name mapping

e.g.: `server: &#aaaaaa&Name`

**Comment by KiWinger** [comment]
> I think you'd just put the color before the custom name mapping
> 
> e.g.: `server: &#aaaaaa&Name`

**Error!**

server_display_names:
  lobby: &#00a7a7&L
  pure: &#00a800&P

Background errors when using the above parameters: 
https://pastebin.com/R4EHCQPn

**Comment by alexdev03** [comment]
Try using "&#00a7a7&L" as # is used as comment

**Comment by KiWinger** [comment]
> Try using "&#00a7a7&L" as # is used as comment

I don't understand what you're saying. :-X
My original configuration file is as follows↓
server_display_names:
lobby: &#00a7a7&L
pure: &#00a800&P

Please change directly on this basis, thank you.

**Comment by alexdev03** [comment]
```
server_display_names:
    lobby: "&#00a7a7&L"
    pure: "&#00a800&P"
```
make sure to adjust spaces.

**Comment by KiWinger** [comment]
> ```
> server_display_names:
>     lobby: "&#00a7a7&L"
>     pure: "&#00a800&P"
> ```
> 
> make sure to adjust spaces.

I was updated from 1.6.3 to 1.7.3, and I found that "server_display_names" function was removed. How can I customize the server name now? Use "Placeholders Replacements"? Is there a specific example?

**Comment by alexdev03** [comment]
> > ```
> > server_display_names:
> >     lobby: "&#00a7a7&L"
> >     pure: "&#00a800&P"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > make sure to adjust spaces.
> 
> I was updated from 1.6.3 to 1.7.3, and I found that "server_display_names" function was removed. How can I customize the server name now? Use "Placeholders Replacements"? Is there a specific example?


Hi, yes you can use [placeholders replacements](https://william278.net/docs/velocitab/placeholders-replacements). There isn't an example for your exact case but it's not difficult to implement. It should be something like this according to the old format.

```
placeholder_replacements:
  '%server%':
    - placeholder: lobby
      replacement: &#00a7a7&L
    - placeholder: pure
      replacement: &#00a800&P
 ```

**Comment by KiWinger** [comment]
> > > ```
> > > server_display_names:
> > >     lobby: "&#00a7a7&L"
> > >     pure: "&#00a800&P"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > make sure to adjust spaces.
> > 
> > 
> > I was updated from 1.6.3 to 1.7.3, and I found that "server_display_names" function was removed. How can I customize the server name now? Use "Placeholders Replacements"? Is there a specific example?
> 
> Hi, yes you can use [placeholders replacements](https://william278.net/docs/velocitab/placeholders-replacements). There isn't an example for your exact case but it's not difficult to implement. It should be something like this according to the old format.
> 
> ```
> placeholder_replacements:
>   '%server%':
>     - placeholder: lobby
>       replacement: &#00a7a7&L
>     - placeholder: pure
>       replacement: &#00a800&P
> ```

It crashed.
Crash output: https://pastebin.com/hrNJxQWZ

**Comment by alexdev03** [comment]
> > > > ```
> > > > server_display_names:
> > > >     lobby: "&#00a7a7&L"
> > > >     pure: "&#00a800&P"
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > make sure to adjust spaces.
> > > 
> > > 
> > > I was updated from 1.6.3 to 1.7.3, and I found that "server_display_names" function was removed. How can I customize the server name now? Use "Placeholders Replacements"? Is there a specific example?
> > 
> > Hi, yes you can use [placeholders replacements](https://william278.net/docs/velocitab/placeholders-replacements). There isn't an example for your exact case but it's not difficult to implement. It should be something like this according to the old format.
> > 
> > ```
> > placeholder_replacements:
> >   '%server%':
> >     - placeholder: lobby
> >       replacement: &#00a7a7&L
> >     - placeholder: pure
> >       replacement: &#00a800&P
> > ```
> 
> It crashed.
> Crash output: https://pastebin.com/hrNJxQWZ

Surround strings with double quotes
