### ISSUE TITLE
Disable header/footer completely

### ISSUE THREAD

**Issue by KabanFriends** [WiIIiam278/Velocitab#173]
This plugin should be able to disable header/footer completely so that it can instead be handled by backend server plugins to display information specific to each backend server

**Comment by WiIIiam278** [comment]
I thought we did do this? Like, if you don't set a header/footer for a group it won't send that data :). We even have an option to turn on/off the auto-clear-header/footer to allow backend plugins to completely overwrite this functionality.

**Comment by alexdev03** [comment]
I think he's right. If the header/footer is empty, we should not send it to the client. We could do this with a new option in the config or make it a default functionality.

> I thought we did do this? Like, if you don't set a header/footer for a group it won't send that data :). We even have an option to turn on/off the auto-clear-header/footer to allow backend plugins to completely overwrite this functionality.
> 
> Thoughts @alexdev03 ?

**Comment by alexdev03** [comment]
Added with: https://github.com/WiIIiam278/Velocitab/pull/176
