### ISSUE TITLE
Disapearing from tab

### ISSUE THREAD

**Issue by courat-private** [WiIIiam278/Velocitab#175]
When i'm kicked from a server, and Velocity reconnect me to a backend server, i disapear from the tablist, any fix please ? like a scheduler or something else, thanks

**Comment by sluhtie** [comment]
Hello, I have encountered the same Issues.

Here are my current server versions:
![grafik](https://github.com/WiIIiam278/Velocitab/assets/97464371/886e3ae2-2e51-440f-9f13-8efe4e4fd0f5)

There weren't any errors in console what so ever. Logs are clear.
I could reproduce this issue by joining one server and using the kick command to kick myself to the hub. Neither my skin was loaded such as the tab.

List of my plugins: (Paper and Velocity)
![grafik](https://github.com/WiIIiam278/Velocitab/assets/97464371/c8482563-26b7-44eb-a8a1-80c4c56092cc)

**Comment by courat-private** [comment]
Same, running latest Velocity, with Paper 1.8.8 no plugins, I fixed it myself by checking the disconnect player event class

**Comment by courat-private** [comment]
bug still present on latest @alexdev03

**Comment by courat-private** [comment]
comes from TabListListener.java@60 -> event.getResult() instanceof KickedFromServerEvent.RedirectPlayer

**Comment by WiIIiam278** [comment]
> comes from TabListListener.java@60 -> event.getResult() instanceof KickedFromServerEvent.RedirectPlayer

PRs welcome?

**Comment by courat-private** [comment]
> > comes from TabListListener.java@60 -> event.getResult() instanceof KickedFromServerEvent.RedirectPlayer
> 
> PRs welcome?

created, but not the best fix, i'm not used to create things with Velocity

**Comment by alexdev03** [comment]
@courat-private @sluhtie Could you open a ticket on discord so we can investigate this problem. Thanks.
