### ISSUE TITLE
only_list_players_in_same_server setting for each group

### ISSUE THREAD

**Issue by sluhtie** [WiIIiam278/Velocitab#179]
There should be an option to enable or disable whether players from the same group should be shown in the same tablist on every server within the group, similar to the only_list_players_in_same_group option in config, but for each group.

For instance, if there's a group named "gameservers," all servers in this group should share the same settings such as header and footer. However, individual servers within this group should only display players from their respective server, rather than showing all players from the entire group.

**Comment by WiIIiam278** [comment]
Closed by #180
