### ISSUE TITLE
Pipe-defined multiline yaml string blocks used in headers/footers erroneously append a line break

### ISSUE THREAD

**Issue by SeemWind** [WiIIiam278/Velocitab#193]
![image](https://github.com/WiIIiam278/Velocitab/assets/50366675/1d228f43-f0e0-4645-9adb-3cbf2afc5884)

the footers in config is like this

```
footers:
  - |
    \n&7For Velocity proxy servers:
    &#1bd96a-#6cffa9&https://modrinth.com/plugin/velocitab
    &#1bd96a-#6cffa9&https://william278.net/project/veloictab'
```

there shouldn't be a blank line in the last

**Comment by WiIIiam278** [comment]
I suspect this is actually a further-upstream issue, either with Exll's configlib - or _possibly_ further up than that? Need to investigate

**Comment by WiIIiam278** [comment]
From Exll, who kindly took a look at the spec for us - If you don't want the final linebreak, you have to use `|-` instead of `|`, i.e.:
```
foo: |-
     bar 1
     bar 2
     bar 3
```
See: https://yaml.org/spec/1.2.2/#example-chomping-final-line-break
