### ISSUE TITLE
Support  JavaScript ISO time custom format

### ISSUE THREAD

**Issue by CuteLittleSky** [WiIIiam278/Velocitab#195]
For %current_date% Placeholder,I hope to use 2023.02.24 instead of 24 Feb 2023
like placeholderapi: %server_time_yy.MM.dd HH:mm:ss%
Because in China, the format of 24 Feb 2023 is not common

**Comment by WiIIiam278** [comment]
Closed in #197 (we now supply individual placeholders for each time unit)
