### ISSUE TITLE
Show all players in tab with different format in each server

### ISSUE THREAD

**Issue by SeemWind** [WiIIiam278/Velocitab#196]
I want to list all players from the proxy, but with different format in tab on each server, how can I do that

**Comment by WiIIiam278** [comment]
You can create groups for each set of servers you wish to format differently and enable the setting to list players in every group/server to achieve this. If you need role-per-server customization, you can use [LuckPerms contexts](https://luckperms.net/wiki/Context) and set prefixes to be based on the `world` context.
