### ISSUE TITLE
Issue with spectator mode noclip

### ISSUE THREAD

**Issue by SeemWind** [WiIIiam278/Velocitab#198]
>Receiving information about going spectator gamemode allows players to clip through walls. Cancelling this on self would result in inability to go through walls.

If I am in spectator gamemode, and rejoin the server, I can't clip through walls. I think velocitab cause this. And this is the explain in plugin [TAB](https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Spectator-fix)

**Comment by WiIIiam278** [comment]
Hi there - I can't reproduce this (latest build as of time of writing).

https://gyazo.com/493995f8f872406996574b3e454bc6b3

Velocitab already has logic to prevent the issue described in TAB's documentation - the `remove_spectator_effect` option _doesn't_ cancel spec mode for the player themselves.

```yaml
# Remove gamemode spectator effect for other players in the TAB list.
remove_spectator_effect: true
```
