### ISSUE TITLE
Duplicated player names

### ISSUE THREAD

**Issue by Tresillo2017** [WiIIiam278/Velocitab#202]
![image](https://github.com/WiIIiam278/Velocitab/assets/56476330/da2520dc-b903-4ce1-99b5-391aa720927d)

[Config.yml](https://pastebin.com/raw/XHZyhaQD)
[tab_groups.yml](https://pastebin.com/raw/JCsSRdBE)

**Comment by alexdev03** [comment]
Hi is your a cracked setup?

**Comment by Tresillo2017** [comment]
> Hi is your a cracked setup?

I'm using librelogin, and online mode is off since the login is made by velocity. Premium users join directly to the server

**Comment by alexdev03** [comment]
Could you join [HuskHelp](https://discord.com/invite/tVYhJfyDWG), there we will be able to give you a better support. Thanks

> > Hi is your a cracked setup?
> 
> I'm using librelogin, and online mode is off since the login is made by velocity. Premium users join directly to the server
