### ISSUE TITLE
Issues with /velocitab reload and header_footer_update_rate

### ISSUE THREAD

**Issue by Jay113355** [WiIIiam278/Velocitab#215]
Velocity version: velocity-3.3.0-415
Velocitab version: Velocitab-1.7

Hey, so I was testing this out and trying to design a animated header-footer when I noticed the animation speed kept jumping frames and being way faster then it was configured to be. After restarting velocity it fixes it and the speed goes back to normal. 

I was able to reproduce the issue again by changing the `header_footer_update_rate` setting and then using `/velocitab reload` a few times.

```
  headers:
  - 'header 1'
  - 'header 2'
  - 'header 3'
  header_footer_update_rate: 10000
```
Switching between 5000 and 10000 does it for me.

**Comment by alexdev03** [comment]
Hi, could you try this build please https://modrinth.com/plugin/velocitab/version/1.7.1-59c8b08

**Comment by alexdev03** [comment]
I can't reproduce that with the latest alpha. [Video](https://imgur.com/a/mtgKJbE )
I also tested the values you provided without finding any issue.
