### ISSUE TITLE
confuse about showcase.png

### ISSUE THREAD

**Issue by shinobi9** [WiIIiam278/Velocitab#22]
can you show a config template like images/showcase.png ? i just query minimessage & minedown docs for implement like the showcase but failed.. thanks

**Comment by WiIIiam278** [comment]
The background showcase is a fairly simple one.
The foreground one is more complex, and uses a resource pack with several re-textured font characters to make up the logo glyph, and some clever formatting for the latter.
Have a look at [the docs](https://william278.net/docs/velocitab) which detail all the different formatting and placeholders you can use.

**Comment by shinobi9** [comment]
sorry, i'm noob with minecraft server  , how to show the avatar and override the default network signal? i find a way to add pings but wont override the vanilla icons.

**Comment by WiIIiam278** [comment]
you need a server resource pack to do that

**Comment by shinobi9** [comment]
thanks.
