### ISSUE TITLE
PlaceholdersAPI randomly does not work for certain player

### ISSUE THREAD

**Issue by nhanledev** [WiIIiam278/Velocitab#231]
Sometimes, one player does not get its name formatted correctly with PlaceholderAPI, no errors are shown on both proxy and backend server.

Switching servers did not help too.

Only player rejoin (disconnect and join again) get this fix.

This behavior happens randomly so I don't know how to reproduce it.

![image](https://github.com/user-attachments/assets/b4f3d5d5-ba27-4af6-82c3-accde94a7587)

Current version: Velocitab-1.7.2, PAPIProxyBridge-Bukkit-1.7

**Comment by nhanledev** [comment]
Anh sometimes it still shows offline player

![image](https://github.com/user-attachments/assets/4aa5434f-b7c3-42c3-a9ac-5be37391d136)

when I kick the player from the proxy, it says that player is offline

**Comment by alexdev03** [comment]
Hi, could you open a ticket, I'm unable to reproduce the problem..

**Comment by nhanledev** [comment]
I cannot reproduce the problem too. It just happens randomly on my production server.

**Comment by alexdev03** [comment]
Hi, as I said before, it would be better if you could open a ticket. Not sure we will be able to fix that since it seems like you are using a cracked setup.

**Comment by FZnachor** [comment]
I have the same problem with MiniPlaceholders. Occasionally, when the player disconnects, his name still stays in the tablist with broken placeholders.

![Image](https://github.com/user-attachments/assets/b0253ba5-c6e0-41fb-b7cc-aba943603162)
