### ISSUE TITLE
Handle forced player remove

### ISSUE THREAD

**Issue by Emibergo02** [WiIIiam278/Velocitab#35]
Some plugins like Cinematic Studio send a "player remove packet" to remove the player when doing spectator things with the camera.
i wonder if it's possible to intercept those remotion and handle them like a normal player quit inside Velocitab.
and then when the plugin send a "player add" handle it like a player join
![image](https://user-images.githubusercontent.com/36164338/229304111-82d827e1-a75c-4d00-b778-ea5cd70c6cd2.png)
no prefix in this case

**Comment by WiIIiam278** [comment]
uhhhhhh maybe? I think we'd need to depend on VPacketEvents and listen out for this if we wanted to handle this. Isn't this just the standard spectator mode TAB thing, though? I figured it already worked with that
