### ISSUE TITLE
TAB refresh error

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [WiIIiam278/Velocitab#51]
If I change the TAB refresh time to 100 or other faster + server players with more than 8-10 players, the player list and RBG title in the TAB will twitch irregularly, and there is no error pointing to this error for the time being

**Comment by WiIIiam278** [comment]
I think the honest fix for this is to impose a minimum TAB time, since <100ms would possibly be sending more than ((1 + num of players * 2) * 10) packets a second, which is liable to introduce race conditions and sync deficiencies due to the sort order being done that much :)

**Comment by xiaoyueyoqwq** [comment]
okay I got it, thanks for your help ;)

**Comment by WiIIiam278** [comment]
Closed by #52
