### ISSUE TITLE
Velocity tab not always updating user's group. 

### ISSUE THREAD

**Issue by GrimPlayzs** [WiIIiam278/Velocitab#62]
When joining or switching to another group will either not display the group name or just display the raw placeholder name in my case this is %luckperms_primary_group_name%

**Comment by WiIIiam278** [comment]
The plugin provides built in LP placeholders for prefix, suffix, group name etc--don't use the PAPI ones!

**Comment by GrimPlayzs** [comment]
In my case, I can't use %prefix% or %role% as in Luckperms they use the minedown format (&) and not the minimessage format which I have velocity tab to use. Only the "displayname group" is in the minimessage format which is passed through %luckperms_primary_group_name% placeholder.

**Comment by WiIIiam278** [comment]
You can change the format being used in Velocitab's config. Do this.

**Comment by GrimPlayzs** [comment]
I would but I rather use minimessage's format for the tab list since it has support for hex colors and gradients.

**Comment by WiIIiam278** [comment]
MineDown also supports hex colors and gradients--please have a look into it

**Comment by GrimPlayzs** [comment]
I changed the format to MineDown as well now using %prefix% which now does properly display every time I join the server and switch to other servers on the network except one which is a fabric server. However when changing my group the prefix does not change in tab unless I do /velocitytab reload

**Comment by GrimPlayzs** [comment]
I should also mention the reason why I was using %luckperms_primary_group_name% in the first place was that it returned the primary group name and not the whole prefix which can be very long if the user is in two groups at once "staff" and "donor" while using %luckperms_primary_group_name% only returns the top group to be shown in tab.

**Comment by GrimPlayzs** [comment]
After further analysis, it seems very inconsistent when it updates I had it update on its own a few times but is not consistent.
