### ISSUE TITLE
Feature Request: %displayname% placeholder or similar.

### ISSUE THREAD

**Issue by GrimPlayzs** [WiIIiam278/Velocitab#63]
![Screenshot 2023-06-06 164521](https://github.com/WiIIiam278/Velocitab/assets/89351648/255144bb-3aa0-4acb-b1ca-5adbe637588f)

Currently, the %role% placeholder only takes the group name and not the displayname of the group which is displayed to the left of the red box or defined as "displayname." The Group name is usually only used by staff or similar to either promote a specific user to that specific group or is used in a plugin's config files. While displayname or the prefix is only used in-game for users to see.

**Comment by WiIIiam278** [comment]
Added `%role_display_name%` placeholder in 07fd9c306aa5c5f0bede692a5bce97dd420c00de :)
