### ISSUE TITLE
Allow Placeholders to form part of sorting keys

### ISSUE THREAD

**Issue by Loren013** [WiIIiam278/Velocitab#70]
Duplicated from discord:

Add a way to sort players in the tablist in alphabetical order of placeholders (Feature that has TAB by NIEZNANY). 
Will be highly appreciated and is so powerful in different ways. We sort players by their clan name (placeholder) (so players in the same clan are displayed together it the TAB)

**Comment by MKieburtz** [comment]
yep, throwing another please into the pile lol. A plugin that does this is bungee tab list plus, on the off chance the code is helpful. https://github.com/CodeCrafter47/BungeeTabListPlus/

**Comment by WiIIiam278** [comment]
Probably the solution would be changing the way that you specify the sorting key to accept a string and just build in the role weight thing as a placeholder

**Comment by alexdev03** [comment]
Added with https://github.com/WiIIiam278/Velocitab/pull/94
