### ISSUE TITLE
Placeholders with color seems not work

### ISSUE THREAD

**Issue by MagmaBlock** [WiIIiam278/Velocitab#76]
```
Velocity 3.2.0-SNAPSHOT (git-37fedf50-b260)
Paper version git-Paper-97 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 1837f6c)

Velocitab 1.4.1
PAPIProxyBridge 1.2.2
```

I try to use Spark's tps placeholder in tab, but after reload the tab stop updating, no error in console.
I replaced with `%server_tps_1%`, it worked. 

But I don't understand, after try I found that placeholder with color will cause this problem, following placeholders are my tried: (they are all colored)
```
%spark_tps%
%server_tps%
%server_tps_1_colored%
%RainbowColor_123123123%
```

**Comment by WiIIiam278** [comment]
Unfortunately that locale seems to pass formatted color data via selection symbols which makes it unreliable. I can’t really provide a fix for this other than suggesting that if you need to use it you try one of the other different formatting modes
