### ISSUE TITLE
Add support for updating player name tags

### ISSUE THREAD

**Issue by sluhtie** [WiIIiam278/Velocitab#81]
Would it be possible to add a support to also change name tags? Maybe add an option in the config to toggle this feature as well.

**Comment by WiIIiam278** [comment]
Low priority feature for me, and pretty unlikely to be added -- this requires me bulking up the plugin with a ton of logic to either do even more hacky stuff with scoreboards or armor stands on backend servers, which goes against my general ethos. We'll see, but don't count on this one.
