### ISSUE TITLE
Velocity. If the player switches Servers seems to have 2 animation threads

### ISSUE THREAD

**Issue by ChiAkuma** [WiIIiam278/Velocitab#86]
Hello, i discovered a problem on Velocity v3.2.0 and Velocitab v1.4.1.
If a player switches between the server the animation is not played in the correct way.
It seems like the animation is played on multiple threads then and randomly switches between them. This causes the animation to not look as expected.

Here is my config for testing things: (It forces me to make it txt)
[config.txt](https://github.com/WiIIiam278/Velocitab/files/12566497/config.txt)

**Comment by Emibergo02** [comment]
Do you have a video?
