### ISSUE TITLE
Show only players in current server group

### ISSUE THREAD

**Issue by TheKrafter** [WiIIiam278/Velocitab#91]
By default, Velocitab shows ALL players in the tab list.

There should be an option in the config to only show the players connected to servers in a given player's current server group in their tab list.

**Comment by TheKrafter** [comment]
Sorry that sounded so blunt! 

I do appreciate your work this is an amazing plugin

**Comment by WiIIiam278** [comment]
Did you turn only_list_players_in_same_group: true off?

**Comment by TheKrafter** [comment]
oh my bad! thanks
